{% set name = "tetra" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tetra-{{ version }}.tar.gz
  sha256: 6c71f07bd2480e20d1ded92ce4bf56ac8e75a684d86b04edd648bcd0fe4c51c3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >=3.8
    - cryptography >=37.0.1
    - django >=3.2.0
    - python-dateutil >=2.8.2
    - django-environ

test:
  imports:
    - tetra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.tetraframework.com/
  dev_url: https://github.com/tetra-framework/tetra
  doc_url: https://tetra.readthedocs.org/
  summary: Full stack component framework for Django using Alpine.js
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
