{% set name = "tetra" %}
{% set version = "0.3.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tetra-{{ version }}.tar.gz
  sha256: 93c5b074ad6806d46d2e846e93cdee05491f52f14b56d5567d37836d6b9d7f72

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - cryptography >=37.0.1
    - django >=3.2.0
    - python-dateutil >=2.8.2
    - sourcetypes >=0.0.4

test:
  imports:
    - tetra
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.tetraframework.com/
  dev_url: https://github.com/tetra-framework/tetra
  doc_url: https://tetra.readthedocs.org/
  summary: Full stack component framework for Django using Alpine.js
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
