schema_version: 1

context:
  name: tetra
  version: "0.9.0"
  python_min: '3.13'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/tetra-${{ version }}.tar.gz
  sha256: a76e5a73e16cb92e6448f401578e3ed478078fc6b91da241ca074c36a2da62ef

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - cryptography >=37.0.1
    - django >=5.2.3
    - python-dateutil >=2.8.2
    - sourcetypes >=0.0.4
    - pydantic

tests:
  - python:
      imports:
        - tetra
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Full stack component framework for Django using Alpine.js
  license: MIT
  license_file: LICENSE
  homepage: https://www.tetraframework.com/
  repository: https://github.com/tetra-framework/tetra
  documentation: https://tetra.readthedocs.org/

extra:
  recipe-maintainers:
    - thewchan
