schema_version: 1

context:
  name: tetra
  version: "0.5.0"
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/tetra-${{ version }}.tar.gz
  sha256: e59b02387341b62b85c28d6a3c0535c15e8aed5d5f305fb6962a7377e290c407

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77.0.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - cryptography >=37.0.1
    - django >=3.2.0
    - python-dateutil >=2.8.2
    - sourcetypes >=0.0.4

tests:
  - python:
      imports:
        - tetra
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Full stack component framework for Django using Alpine.js
  license: MIT
  license_file: LICENSE
  homepage: https://www.tetraframework.com/
  repository: https://github.com/tetra-framework/tetra
  documentation: https://tetra.readthedocs.org/

extra:
  recipe-maintainers:
    - thewchan
